name: Deploy FastAPI to AWS Lambda

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Serverless CLI via pipx
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipx
          pipx ensurepath
          pipx install "serverless<4"

      - name: Install Python dependencies
        working-directory: backend
        run: |
          python -m pip install -r requirements.txt

      - name: Deploy to AWS Lambda
        working-directory: backend 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: serverless deploy